import type { Group, KnockoutMatch, Team } from '@/types/tournament';

export const GROUP_IDS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];

export const fixtureTeams: Team[] = [
  { id: 'mex', name: 'Mexico', code: 'MEX', group: 'A' },
  { id: 'kor', name: 'South Korea', code: 'KOR', group: 'A' },
  { id: 'rsa', name: 'South Africa', code: 'RSA', group: 'A' },
  { id: 'cze', name: 'Czechia', code: 'CZE', group: 'A' },
  { id: 'can', name: 'Canada', code: 'CAN', group: 'B' },
  { id: 'sui', name: 'Switzerland', code: 'SUI', group: 'B' },
  { id: 'qat', name: 'Qatar', code: 'QAT', group: 'B' },
  { id: 'bih', name: 'Bosnia and Herzegovina', code: 'BIH', group: 'B' },
  { id: 'bra', name: 'Brazil', code: 'BRA', group: 'C' },
  { id: 'mar', name: 'Morocco', code: 'MAR', group: 'C' },
  { id: 'sco', name: 'Scotland', code: 'SCO', group: 'C' },
  { id: 'hai', name: 'Haiti', code: 'HAI', group: 'C' },
  { id: 'usa', name: 'United States', code: 'USA', group: 'D' },
  { id: 'par', name: 'Paraguay', code: 'PAR', group: 'D' },
  { id: 'aus', name: 'Australia', code: 'AUS', group: 'D' },
  { id: 'tur', name: 'Türkiye', code: 'TUR', group: 'D' },
  { id: 'ger', name: 'Germany', code: 'GER', group: 'E' },
  { id: 'ecu', name: 'Ecuador', code: 'ECU', group: 'E' },
  { id: 'civ', name: 'Ivory Coast', code: 'CIV', group: 'E' },
  { id: 'cuw', name: 'Curaçao', code: 'CUW', group: 'E' },
  { id: 'ned', name: 'Netherlands', code: 'NED', group: 'F' },
  { id: 'jpn', name: 'Japan', code: 'JPN', group: 'F' },
  { id: 'tun', name: 'Tunisia', code: 'TUN', group: 'F' },
  { id: 'swe', name: 'Sweden', code: 'SWE', group: 'F' },
  { id: 'bel', name: 'Belgium', code: 'BEL', group: 'G' },
  { id: 'irn', name: 'Iran', code: 'IRN', group: 'G' },
  { id: 'egy', name: 'Egypt', code: 'EGY', group: 'G' },
  { id: 'nzl', name: 'New Zealand', code: 'NZL', group: 'G' },
  { id: 'esp', name: 'Spain', code: 'ESP', group: 'H' },
  { id: 'uru', name: 'Uruguay', code: 'URU', group: 'H' },
  { id: 'sau', name: 'Saudi Arabia', code: 'KSA', group: 'H' },
  { id: 'cpv', name: 'Cape Verde', code: 'CPV', group: 'H' },
  { id: 'fra', name: 'France', code: 'FRA', group: 'I' },
  { id: 'sen', name: 'Senegal', code: 'SEN', group: 'I' },
  { id: 'nor', name: 'Norway', code: 'NOR', group: 'I' },
  { id: 'irq', name: 'Iraq', code: 'IRQ', group: 'I' },
  { id: 'arg', name: 'Argentina', code: 'ARG', group: 'J' },
  { id: 'aut', name: 'Austria', code: 'AUT', group: 'J' },
  { id: 'alg', name: 'Algeria', code: 'ALG', group: 'J' },
  { id: 'jor', name: 'Jordan', code: 'JOR', group: 'J' },
  { id: 'por', name: 'Portugal', code: 'POR', group: 'K' },
  { id: 'col', name: 'Colombia', code: 'COL', group: 'K' },
  { id: 'uzb', name: 'Uzbekistan', code: 'UZB', group: 'K' },
  { id: 'cod', name: 'DR Congo', code: 'COD', group: 'K' },
  { id: 'eng', name: 'England', code: 'ENG', group: 'L' },
  { id: 'cro', name: 'Croatia', code: 'CRO', group: 'L' },
  { id: 'pan', name: 'Panama', code: 'PAN', group: 'L' },
  { id: 'gha', name: 'Ghana', code: 'GHA', group: 'L' },
];

export const fixtureGroups: Group[] = GROUP_IDS.map((id) => ({
  id,
  name: `Group ${id}`,
  teams: fixtureTeams.filter((t) => t.group === id),
}));

export const fixtureKnockoutMatches: KnockoutMatch[] = [
  { id: 'M73', stage: 'round_of_32', team1Source: '1A', team2Source: '2B', pointValue: 2 },
  { id: 'M74', stage: 'round_of_32', team1Source: '1C', team2Source: '2D', pointValue: 2 },
  { id: 'M75', stage: 'round_of_32', team1Source: '1E', team2Source: '2F', pointValue: 2 },
  { id: 'M76', stage: 'round_of_32', team1Source: '1G', team2Source: '2H', pointValue: 2 },
  { id: 'M77', stage: 'round_of_32', team1Source: '1I', team2Source: '2J', pointValue: 2 },
  { id: 'M78', stage: 'round_of_32', team1Source: '1K', team2Source: '2L', pointValue: 2 },
  { id: 'M79', stage: 'round_of_32', team1Source: '1B', team2Source: '2A', pointValue: 2 },
  { id: 'M80', stage: 'round_of_32', team1Source: '1D', team2Source: '2C', pointValue: 2 },
  { id: 'M81', stage: 'round_of_32', team1Source: '1F', team2Source: '2E', pointValue: 2 },
  { id: 'M82', stage: 'round_of_32', team1Source: '1H', team2Source: '2G', pointValue: 2 },
  { id: 'M83', stage: 'round_of_32', team1Source: '1J', team2Source: '2I', pointValue: 2 },
  { id: 'M84', stage: 'round_of_32', team1Source: '1L', team2Source: '2K', pointValue: 2 },
  { id: 'M85', stage: 'round_of_32', team1Source: '3A', team2Source: '3B', pointValue: 2 },
  { id: 'M86', stage: 'round_of_32', team1Source: '3C', team2Source: '3D', pointValue: 2 },
  { id: 'M87', stage: 'round_of_32', team1Source: '3E', team2Source: '3F', pointValue: 2 },
  { id: 'M88', stage: 'round_of_32', team1Source: '3G', team2Source: '3H', pointValue: 2 },
  { id: 'M89', stage: 'round_of_16', team1Source: 'M74', team2Source: 'M77', pointValue: 4 },
  { id: 'M90', stage: 'round_of_16', team1Source: 'M73', team2Source: 'M75', pointValue: 4 },
  { id: 'M91', stage: 'round_of_16', team1Source: 'M76', team2Source: 'M78', pointValue: 4 },
  { id: 'M92', stage: 'round_of_16', team1Source: 'M79', team2Source: 'M80', pointValue: 4 },
  { id: 'M93', stage: 'round_of_16', team1Source: 'M83', team2Source: 'M84', pointValue: 4 },
  { id: 'M94', stage: 'round_of_16', team1Source: 'M81', team2Source: 'M82', pointValue: 4 },
  { id: 'M95', stage: 'round_of_16', team1Source: 'M86', team2Source: 'M88', pointValue: 4 },
  { id: 'M96', stage: 'round_of_16', team1Source: 'M85', team2Source: 'M87', pointValue: 4 },
  { id: 'M97', stage: 'quarter_finals', team1Source: 'M89', team2Source: 'M90', pointValue: 8 },
  { id: 'M98', stage: 'quarter_finals', team1Source: 'M93', team2Source: 'M94', pointValue: 8 },
  { id: 'M99', stage: 'quarter_finals', team1Source: 'M91', team2Source: 'M92', pointValue: 8 },
  { id: 'M100', stage: 'quarter_finals', team1Source: 'M95', team2Source: 'M96', pointValue: 8 },
  { id: 'M101', stage: 'semi_finals', team1Source: 'M97', team2Source: 'M98', pointValue: 15 },
  { id: 'M102', stage: 'semi_finals', team1Source: 'M99', team2Source: 'M100', pointValue: 15 },
  { id: 'M103', stage: 'third_place', team1Source: 'L-M101', team2Source: 'L-M102', pointValue: 10 },
  { id: 'M104', stage: 'final', team1Source: 'M101', team2Source: 'M102', pointValue: 25 },
];
