import type { Group, KnockoutMatch, Team } from '@/types/tournament';

export const GROUP_IDS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];

export const fixtureTeams: Team[] = [
  { id: 'mex', name: 'Mexico', code: 'MEX', group: 'A' },
  { id: 'kor', name: 'South Korea', code: 'KOR', group: 'A' },
  { id: 'rsa', name: 'South Africa', code: 'RSA', group: 'A' },
  { id: 'cze', name: 'Czechia', code: 'CZE', group: 'A' },
  { id: 'can', name: 'Canada', code: 'CAN', group: 'B' },
  { id: 'sui', name: 'Switzerland', code: 'SUI', group: 'B' },
  { id: 'qat', name: 'Qatar', code: 'QAT', group: 'B' },
  { id: 'bih', name: 'Bosnia and Herzegovina', code: 'BIH', group: 'B' },
  { id: 'bra', name: 'Brazil', code: 'BRA', group: 'C' },
  { id: 'mar', name: 'Morocco', code: 'MAR', group: 'C' },
  { id: 'sco', name: 'Scotland', code: 'SCO', group: 'C' },
  { id: 'hai', name: 'Haiti', code: 'HAI', group: 'C' },
  { id: 'usa', name: 'United States', code: 'USA', group: 'D' },
  { id: 'par', name: 'Paraguay', code: 'PAR', group: 'D' },
  { id: 'aus', name: 'Australia', code: 'AUS', group: 'D' },
  { id: 'tur', name: 'Türkiye', code: 'TUR', group: 'D' },
  { id: 'ger', name: 'Germany', code: 'GER', group: 'E' },
  { id: 'ecu', name: 'Ecuador', code: 'ECU', group: 'E' },
  { id: 'civ', name: 'Ivory Coast', code: 'CIV', group: 'E' },
  { id: 'cuw', name: 'Curaçao', code: 'CUW', group: 'E' },
  { id: 'ned', name: 'Netherlands', code: 'NED', group: 'F' },
  { id: 'jpn', name: 'Japan', code: 'JPN', group: 'F' },
  { id: 'tun', name: 'Tunisia', code: 'TUN', group: 'F' },
  { id: 'swe', name: 'Sweden', code: 'SWE', group: 'F' },
  { id: 'bel', name: 'Belgium', code: 'BEL', group: 'G' },
  { id: 'irn', name: 'Iran', code: 'IRN', group: 'G' },
  { id: 'egy', name: 'Egypt', code: 'EGY', group: 'G' },
  { id: 'nzl', name: 'New Zealand', code: 'NZL', group: 'G' },
  { id: 'esp', name: 'Spain', code: 'ESP', group: 'H' },
  { id: 'uru', name: 'Uruguay', code: 'URU', group: 'H' },
  { id: 'sau', name: 'Saudi Arabia', code: 'KSA', group: 'H' },
  { id: 'cpv', name: 'Cape Verde', code: 'CPV', group: 'H' },
  { id: 'fra', name: 'France', code: 'FRA', group: 'I' },
  { id: 'sen', name: 'Senegal', code: 'SEN', group: 'I' },
  { id: 'nor', name: 'Norway', code: 'NOR', group: 'I' },
  { id: 'irq', name: 'Iraq', code: 'IRQ', group: 'I' },
  { id: 'arg', name: 'Argentina', code: 'ARG', group: 'J' },
  { id: 'aut', name: 'Austria', code: 'AUT', group: 'J' },
  { id: 'alg', name: 'Algeria', code: 'ALG', group: 'J' },
  { id: 'jor', name: 'Jordan', code: 'JOR', group: 'J' },
  { id: 'por', name: 'Portugal', code: 'POR', group: 'K' },
  { id: 'col', name: 'Colombia', code: 'COL', group: 'K' },
  { id: 'uzb', name: 'Uzbekistan', code: 'UZB', group: 'K' },
  { id: 'cod', name: 'DR Congo', code: 'COD', group: 'K' },
  { id: 'eng', name: 'England', code: 'ENG', group: 'L' },
  { id: 'cro', name: 'Croatia', code: 'CRO', group: 'L' },
  { id: 'pan', name: 'Panama', code: 'PAN', group: 'L' },
  { id: 'gha', name: 'Ghana', code: 'GHA', group: 'L' },
];

export const fixtureGroups: Group[] = GROUP_IDS.map((id) => ({
  id,
  name: `Group ${id}`,
  teams: fixtureTeams.filter((t) => t.group === id),
}));

export const fixtureKnockoutMatches: KnockoutMatch[] = [
  { id: 'M1', stage: 'round_of_32', team1Source: '1A', team2Source: '2B', pointValue: 2 },
  { id: 'M2', stage: 'round_of_32', team1Source: '1C', team2Source: '2D', pointValue: 2 },
  { id: 'M3', stage: 'round_of_32', team1Source: '1E', team2Source: '2F', pointValue: 2 },
  { id: 'M4', stage: 'round_of_32', team1Source: '1G', team2Source: '2H', pointValue: 2 },
  { id: 'M5', stage: 'round_of_32', team1Source: '1I', team2Source: '2J', pointValue: 2 },
  { id: 'M6', stage: 'round_of_32', team1Source: '1K', team2Source: '2L', pointValue: 2 },
  { id: 'M7', stage: 'round_of_32', team1Source: '1B', team2Source: '2A', pointValue: 2 },
  { id: 'M8', stage: 'round_of_32', team1Source: '1D', team2Source: '2C', pointValue: 2 },
  { id: 'M9', stage: 'round_of_32', team1Source: '1F', team2Source: '2E', pointValue: 2 },
  { id: 'M10', stage: 'round_of_32', team1Source: '1H', team2Source: '2G', pointValue: 2 },
  { id: 'M11', stage: 'round_of_32', team1Source: '1J', team2Source: '2I', pointValue: 2 },
  { id: 'M12', stage: 'round_of_32', team1Source: '1L', team2Source: '2K', pointValue: 2 },
  { id: 'M13', stage: 'round_of_32', team1Source: '3A', team2Source: '3B', pointValue: 2 },
  { id: 'M14', stage: 'round_of_32', team1Source: '3C', team2Source: '3D', pointValue: 2 },
  { id: 'M15', stage: 'round_of_32', team1Source: '3E', team2Source: '3F', pointValue: 2 },
  { id: 'M16', stage: 'round_of_32', team1Source: '3G', team2Source: '3H', pointValue: 2 },
  { id: 'M17', stage: 'round_of_16', team1Source: 'M1', team2Source: 'M2', pointValue: 4 },
  { id: 'M18', stage: 'round_of_16', team1Source: 'M3', team2Source: 'M4', pointValue: 4 },
  { id: 'M19', stage: 'round_of_16', team1Source: 'M5', team2Source: 'M6', pointValue: 4 },
  { id: 'M20', stage: 'round_of_16', team1Source: 'M7', team2Source: 'M8', pointValue: 4 },
  { id: 'M21', stage: 'round_of_16', team1Source: 'M9', team2Source: 'M10', pointValue: 4 },
  { id: 'M22', stage: 'round_of_16', team1Source: 'M11', team2Source: 'M12', pointValue: 4 },
  { id: 'M23', stage: 'round_of_16', team1Source: 'M13', team2Source: 'M14', pointValue: 4 },
  { id: 'M24', stage: 'round_of_16', team1Source: 'M15', team2Source: 'M16', pointValue: 4 },
  { id: 'M25', stage: 'quarter_finals', team1Source: 'M17', team2Source: 'M18', pointValue: 8 },
  { id: 'M26', stage: 'quarter_finals', team1Source: 'M19', team2Source: 'M20', pointValue: 8 },
  { id: 'M27', stage: 'quarter_finals', team1Source: 'M21', team2Source: 'M22', pointValue: 8 },
  { id: 'M28', stage: 'quarter_finals', team1Source: 'M23', team2Source: 'M24', pointValue: 8 },
  { id: 'M29', stage: 'semi_finals', team1Source: 'M25', team2Source: 'M26', pointValue: 15 },
  { id: 'M30', stage: 'semi_finals', team1Source: 'M27', team2Source: 'M28', pointValue: 15 },
  { id: 'M31', stage: 'third_place', team1Source: 'L-M29', team2Source: 'L-M30', pointValue: 10 },
  { id: 'M32', stage: 'final', team1Source: 'M29', team2Source: 'M30', pointValue: 25 },
];
